# Generated by Django 4.2.3 on 2023-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adpages',
            fields=[
                ('adpage_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('action_name', models.CharField(max_length=225)),
                ('controller_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'adpages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'fraud_detection',
                'managed': True,
            },
        ),
    ]
