# Generated by Django 4.2.3 on 2023-09-12 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adpages',
            fields=[
                ('adpage_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('action_name', models.CharField(max_length=225)),
                ('controller_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'adpages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgot_password_token', models.CharField(max_length=100)),
                ('isVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_table',
                'managed': True,
            },
        ),
    ]
