# Generated by Django 4.2.3 on 2023-09-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstable',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
