# Generated by Django 4.2.3 on 2023-09-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_userstable_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstable',
            name='email_token',
            field=models.CharField(default='NOT Sent', max_length=200),
            preserve_default=False,
        ),
    ]
