# Generated by Django 4.2.3 on 2023-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_userstable_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='email_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userstable',
            name='forgot_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
